name: Build and Deploy Frontend to GitHub Pages
on:
  push:
    branches:
      - main
      - alexanderheffernan/github-pages-hosting
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: '21.2.0'

      - name: Install
        run: |
          npm ci
          npm run build
        working-directory: frontend

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist
          branch: gh-pages
          token: ${{ secrets.GH_PAGES }}
