name: Build and push Frontend Docker image

on:
  push:
    branches: [ "main", "alexanderheffernan/docker-ci" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/docker-frontend.yml'
  workflow_dispatch:

concurrency:
  group: docker-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-frontend:
    runs-on: [self-hosted, truenas]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-race-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max