name: Build and push Docker images to Docker Hub

on: 
  push:
    branches: [ "main", "alexanderheffernan/docker-ci" ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/docker.yml'
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
              - '.github/workflows/docker.yml'
            backend:
              - 'backend/**'
              - '.github/workflows/docker.yml'

  build-frontend:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    concurrency:
      group: docker-deploy-${{ github.ref }}-frontend
      cancel-in-progress: true
    runs-on: [self-hosted, truenas]
    name: Build and push frontend Docker image
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-race-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-backend:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    concurrency:
      group: docker-deploy-${{ github.ref }}-backend
      cancel-in-progress: true
    runs-on: [self-hosted, truenas]
    name: Build and push backend Docker image
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-race-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max